name: Lint

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          filter_mode: nofilter
          fail_on_error: true
          level: info
